version: '3'

services:
  app:
    build:
      context: '..'
      dockerfile: .devcontainer/Dockerfile

    image: react-tutorial
    container_name: app

    # command: npx nodemon index.js
    ports:
      - '3000:3000'
    volumes:
      - ..:/workspaces/react-tutorial
      - node_modules:/workspaces/react-tutorial/node_modules
    working_dir: /workspaces/react-tutorial
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      TZ: Asia/Tokyo
    tty: true

volumes:
  node_modules:
